### ISSUE TITLE
Documentation muster-server

### ISSUE THREAD

**Issue by fabien** [dwstech/muster#15]
**Describe the bug**

I believe the documentation on this page https://dwstech.github.io/muster/docs/tutorials/muster-server.html is incorrect. More specifically, the last example, where a WS is used to set the name, I think the key/ref should contain `server` as the branch prefix on the client:

```javascript
await clientApp.resolve(set(ref('server', 'name'), 'Kate'));
```
Interesting project by the way! I have been using https://github.com/Yomguithereal/baobab in my projects, which appears to share some of the concepts muster is built around. Muster appears to take this quite a step further though. I'm curious, given the v.6.5.0 - has it been in production for a long time? If so, where is it used?

**Comment by dws-dave** [comment]
Hi Fabien, you're right: the doc is out of date. We'll have a fix for that going in very soon.

Muster has been used internally in DWS Tech for a good long while, and we're pretty strict about semver hence the significant major version. 6.5.0 is the first public release, there will definitely be more to come.

**Comment by dws-dave** [comment]
Closed via #20

**Comment by dws-adam** [comment]
Just for your interest @fabien, Baobab was one of (a number of) inspirations back when we started muster more than 2 years ago.

**Comment by fabien** [comment]
@dws-adam interesting! Looks like Muster is a solid contender to replace Baobab for me eventually. 

What attracts me towards Muster is the transparent async handling, and the ability to work with remote graphs. Do you expect it to be used in more write-heavy API situations as well? To replace REST for example? I haven't checked, but I presume actions (or fn) defined on the remote tree can be called from the client as well? Without further restrictions? 

I guess it doesn't make much sense, but will there ever be a precompiled `dist/` version of Muster? ES5/AMD compatible perhaps?

By the way, is the new documentation already live? The issue mentioned here doesn't seem to be fixed - unless I was wrong in the first place of course!

**Comment by dws-dave** [comment]
Hi @fabien, we've not versioned the docs again since the change went in (as we've not released a new version), so the fix is on [docs/next](https://dwstech.github.io/muster/docs/next/tutorials/muster-server). We may have to look at how we update and version Docusaurus if this sort of thing keeps happening 🤔

You can absolutely call actions and fns on a remote server from a client, so write-heavy applications should be no barrier. We do package a `umd` bundle of `muster` and `muster-react`, but we don't use them internally so they could definitely use some road-testing!

**Comment by fabien** [comment]
I didn't want to open a new issue for this, but I was just wondering about the deployment bundle size of an app built around Muster. I finally got a chance to play around with it in a webpack/babel app, and just including Muster yields a 440 Kb bundle size. I presume there's little to do about that?

**Comment by dws-laurence** [comment]
@fabien Using the esm modules from muster lets it tree-shake, but at the moment we haven't been able to get the core library smaller than 100kb (unless gzipped).

At a minimum adding muster-react will add about 20kb, but as you do more it can increase significantly.

We're looking at improving this and have done a few experiments with it, though it's proven a little tricky to get it to tree-shake much further. Hopefully we can continue to reduce its size over time :)

(These numbers were on a create-react-app with just a simple graph and provider, the total came to about ~250kb pre-gzip).

**Comment by fabien** [comment]
@dws-laurence I will have to investigate with tree-shaking then, thanks. Just adding muster itself added up to 400+ Kb already for me.

**Comment by dws-dave** [comment]
@fabien If you're using webpack 4+ (which I believe CRA is), it should read the [`module` entry](https://github.com/dwstech/muster/blob/develop/packages/muster/package.json#L5) from dependent package.jsons and import from the `esm` folder instead. A standard import statement should allow webpack to tree-shake on build.

```jsx
import muster from '@dws/muster';
import { Provider } from '@dws/muster-react';

const app = muster({
  key: 'string',
});

class App extends Component {
  render() {
    return (
      <Provider muster={app}>
        <div className="App">
          // ...
```

This block should "only" add ~140kb unzipped to your prod bundle. Let us know (on a new issue, I guess) if that doesn't match what you're seeing!
