### ISSUE TITLE
Fix a problem in switchOn() node documentation

### ISSUE THREAD

**Issue by tmikus** [dwstech/muster#39]
**Describe the bug**
The `switchOn()` node documentation page has invalid links to [[when]] node.

**To Reproduce**
1. Navigate to https://dwstech.github.io/muster/api/latest/modules/muster.html#switchon
2. Notice incorrectly named references to [[case]] node

**Expected behavior**
The documentation should mention [[when]] node.

**Screenshots**
<img width="783" alt="screenshot 2018-12-27 at 17 25 02" src="https://user-images.githubusercontent.com/744210/50486976-b5527780-09fc-11e9-9945-52ff102d3e3d.png">

**Comment by dws-dave** [comment]
Closed via #41
